applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: ${github_repo_url}
      path: charts/django-app
      targetRevision: final_project
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: kube-prometheus-stack
    namespace: argocd
    project: default
    source:
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 45.5.0
      helm:
        values: |
          namespaceOverride: monitoring
          prometheus:
            service:
              type: ClusterIP
            prometheusSpec:
              replicas: 1
              retention: 10d
              serviceMonitorSelectorNilUsesHelmValues: false
              serviceMonitorSelector:
                matchLabels:
                  release: monitoring
          grafana:
            enabled: true
            service:
              type: ClusterIP
            adminPassword: admin
            defaultDashboardsEnabled: true
          alertmanager:
            enabled: true
            service:
              type: ClusterIP
            alertmanagerSpec:
              replicas: 1
          pushgateway:
            enabled: true
            service:
              type: ClusterIP
            serviceMonitor:
              enabled: true
              interval: 15s
              labels:
                release: monitoring
    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

  - name: django-db-secret
    namespace: default
    project: default
    source:
      repoURL: ${github_repo_url}
      path: charts/secret
      targetRevision: final_project
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
